// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/darmi-layouts/BentoGrid.tsx": () => import("../components/mockups/darmi-layouts/BentoGrid.tsx"),
  "./components/mockups/darmi-layouts/CenteredEditorial.tsx": () => import("../components/mockups/darmi-layouts/CenteredEditorial.tsx"),
  "./components/mockups/darmi-layouts/SplitAsymmetric.tsx": () => import("../components/mockups/darmi-layouts/SplitAsymmetric.tsx")
};
